version: '3.8'

services:
  app_dev:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
    container_name: app_dev
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  db_dev:
    image: postgres:15-alpine
    container_name: db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: club_name
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: